### PR TITLE
Update for mongodb 4.0 nodejs driver

### PR DESCRIPTION
**Pull request by eugeniop**

### CODE REVIEW

**Comment by webfrank** [comment]
Hi, please merge this to be able to use latest driver.

**Comment by mhassan1** [comment]
I've just published fork [mongodb-queue-up](https://www.npmjs.com/package/mongodb-queue-up) with support for `mongodb@4`.

**Comment by vpalos** [comment]
Hey @chilts and @mhassan1! Great work, first of all!

But is there a reason to keep the fork, now that the changes are merge in the original repo?
Can you please publish the new version (5) in NPM?

Right now, we're left with 2 options: use the GIT repo as dependency, or the forked package provided by @mhassan1.

**Comment by benediktask** [comment]
Just an innocent bump up. I concur with @vpalos, could we have this published via npm? @chilts

**Pull request merged**
